### ISSUE TITLE
Not able to run any baseline example due to missing entry point

### ISSUE THREAD

**Issue by Ujwal2910** [openai/baselines#982] opened 2019-08-09 08:07 UTC
while running this-

command - python3 -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7
Traceback (most recent call last):
  File "/home/ujwal/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ujwal/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)

in run.py, line 35, in <module>
    env_type = env.entry_point.split(':')[0].split('.')[-1]
AttributeError: 'EnvSpec' object has no attribute 'entry_point'

**Comment by DanielTakeshi** [comment] 2019-08-09 18:26
Looks like https://github.com/openai/baselines/issues/977 has the same error

**Comment by Ujwal2910** [comment] 2019-08-11 19:02
I was able to resolve this issue by changing-
env_type = env.entry_point.split(':')[0].split('.')[-1] 
to
env_type = env._entry_point.split(':')[0].split('.')[-1]
Basically its not able to recognize the change which was recently made in the repository by replacing _entry_point to just entry_point.
I am also running the latest GYM version so not an issue in that.

**Comment by christopherhesse** [comment] 2019-10-25 22:50
What version of baselines are you using?

**Comment by christopherhesse** [comment] 2019-11-08 23:16
duplicate of https://github.com/openai/baselines/issues/977

**Closed by christopherhesse** 2019-11-08 23:16 UTC
