### ISSUE TITLE
Question about FetchPickAndPlace-v2 task 

### ISSUE THREAD

**Issue by huangjiancong1** [openai/baselines#602] opened 2018-09-20 13:08 UTC
As we can see in the [fetch_env ](https://github.com/openai/gym/blob/924d1349398fa7d0a1ec2a8d5e316aef296115c2/gym/envs/robotics/fetch_env.py#L179-L180)file, there have any definition about the robot gripper how to the pick the object success or not, This file only talk about the position. I can only find the descripe about gripper to pick in [pickandplace.xml](https://github.com/openai/gym/blob/924d1349398fa7d0a1ec2a8d5e316aef296115c2/gym/envs/robotics/assets/fetch/pick_and_place.xml#L31-L34) file. 
I find out that Fetch robot playing very will in pickandplace task after DDPG learning. But if i change the other robot which have a different gripper, it play poorly.

**Comment by huangjiancong1** [comment] 2018-09-21 14:56
Is there any approach to set the initial pose of fetch robot?

**Comment by christopherhesse** [comment] 2019-02-09 01:52
Closing as a duplicate of https://github.com/openai/gym/issues/1173

**Closed by christopherhesse** 2019-02-09 01:52 UTC
