### ISSUE TITLE
AttributeError: 'ScaledFloatFrame' object has no attribute 'num_envs'

### ISSUE THREAD

**Issue by MatPoliquin** [openai/baselines#646] opened 2018-10-11 11:06 UTC
When I run:
python3 -m baselines.run --alg=ppo2 --env=SuperMarioBros-Nes --num_timesteps=2e7

I get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fanbingbing/ML/baselines/baselines/run.py", line 239, in <module>
    main()
  File "/home/fanbingbing/ML/baselines/baselines/run.py", line 213, in main
    model, env = train(args, extra_args)
  File "/home/fanbingbing/ML/baselines/baselines/run.py", line 79, in train
    **alg_kwargs
  File "/home/fanbingbing/ML/baselines/baselines/ppo2/ppo2.py", line 295, in learn
    nenvs = env.num_envs
AttributeError: 'ScaledFloatFrame' object has no attribute 'num_envs'
```

I made a temporary fix but get other similar errors further.

Additional info:
Ubuntu 18.04
Python 3.6.6
synced baselines with latest commit: 28aca63

retro env works fine with SuperMario when I test it directly so it's not an issue with retro env not working
Also the example command provided in the readme works fine:
python3 -m baselines.run --alg=ppo2 --env=PongNoFrameskip-v4 --num_timesteps=2e7

**Comment by pzhokhov** [comment] 2018-10-20 01:14
confirmed, will fix shortly

**Comment by MatPoliquin** [comment] 2018-10-20 09:19
@pzhokhov Thanks a lot!

**Comment by pzhokhov** [comment] 2018-10-23 16:58
should be fixed now

**Closed by pzhokhov** 2018-10-23 16:58 UTC

**Comment by MatPoliquin** [comment] 2018-10-25 03:18
After syncing the latest commit and running the exact same command and setup as described above I get this error now:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fanbingbing/ML/baselines/baselines/run.py", line 221, in <module>
    main()
  File "/home/fanbingbing/ML/baselines/baselines/run.py", line 195, in main
    model, env = train(args, extra_args)
  File "/home/fanbingbing/ML/baselines/baselines/run.py", line 78, in train
    **alg_kwargs
  File "/home/fanbingbing/ML/baselines/baselines/ppo2/ppo2.py", line 333, in learn
    obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run() #pylint: disable=E0632
  File "/home/fanbingbing/ML/baselines/baselines/ppo2/ppo2.py", line 184, in run
    mb_obs = np.asarray(mb_obs, dtype=self.obs.dtype)
  File "/home/fanbingbing/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError

**Comment by pzhokhov** [comment] 2018-10-25 03:33
This can be caused by default nsteps being too large. We have the values tuned down for atari games by default, but not retro. You could do that by running with options `--nsteps=128 --nminibatches=4`
(first one decreases the number of rollout steps per update, second - number of minibatches those steps are split into)

**Comment by MatPoliquin** [comment] 2018-10-27 09:15
ok it now works, I added retro defaults for ppo2, make use of the retro deepmind wrapper as well as set 'cnn' as default network. I made pull requests
