### ISSUE TITLE
Ensuring that all envs in a parallelized VecEnv are correctly reset

### ISSUE THREAD

**Issue by DanielTakeshi** [openai/baselines#688] opened 2018-10-29 16:45 UTC
When using [make_vec_env](https://github.com/openai/baselines/blob/master/baselines/common/cmd_util.py) to make a [SubprocVecEnv](https://github.com/openai/baselines/blob/master/baselines/common/vec_env/subproc_vec_env.py) that contains several envs (let's say two envs for now, a.k.a, two CPUs), this lets us step through these two envs in parallel. Let's suppose we create two of these data structures, one for training an agent and another for held-out trajectories, where we observe the performance of the trained model but do not use any of the data for training (so, it's just for evaluation). I changed the paths to where the monitors are stored, so the training and held-out episodes will be held in separate `0.k.monitor.csv` files where `k` is either 0 or 1 depending on the CPU.

Suppose I want to use 3 held-out episodes for evaluation for every 10k steps of training. After 10k steps of training, the logic proceeds like this:

- After n_1 steps, we finished an episode in (for example) the second CPU, which gives reward r_1. Calling `env.step()` internally calls `env.reset()` _for the env in that CPU only_ if a `done` is detected, so we correctly reset.
- After n_2 steps, we finished an episode in (for example) the first CPU, giving reward r_2. Calling `env.step()` will reset the env in the first CPU as expected ...
- After n_3 steps, we finished an episode in (for example) the first CPU, giving reward r_3.

My code then detects that we have 3 episodes, and we return the episode statistics.

However, *the second CPU still has an episode in progress* when we return the episode statistics. After 20k total training steps, the next time we call the held-out trajectory code for evaluation, in the first CPU, we will be starting from scratch, which is what we want. *But the episode in the second CPU will be continuing from where it was last set at*. This means the first part of that episode was created by an older agent beforehand, and the second part was created by the current trained agent! This is completely undesirable.

Is there a way to completely reset all environments in a parallel env, or to simply run all CPU episodes to a `done` completion without proceeding? I tried calling `env.reset()` where `env` is a SubprocVecEnv, but this does not reset all the parallel envs, as I can tell from `env.render()`.

Here's an example code snippet that I have if it helps with DQN (so `act` is the function). I named the env `env2` to avoid confusing it with the `env` that I use for training steps.

```python
def see_immediate_performance(env2, act, num_episodes, render=False, greedy_eps=0.01):
    """To see how well our agent, `act`, does.

    Returns
    -------
    A list of episode rewards.
    """
    obs = env2.reset() 
    completed_eps = 0 
    num_steps = 0 
    estats = []

    while completed_eps < num_episodes:
        actions = act(obs, stochastic=True, update_eps=greedy_eps)
        new_obs, rewards, dones, infos = env2.step(actions)
        if render:
            env2.render()
        num_steps += env2.num_envs
        for (k,done) in enumerate(dones):
            if done and ('episode' in infos[k]):
                estats.append( infos[k]['episode'] )
                completed_eps += 1
        obs = new_obs

    ep_rewards = []
    for ep in estats:
        ep_rewards.append(ep['r'])
    return ep_rewards
```

I can do a temporary workaround by ignoring the first episode in each CPU, but I am hoping there is an easier way if possible.

**Comment by pzhokhov** [comment] 2018-11-02 02:34
It sounds to me like venv.reset() *should* help in your case (by resetting all the sub-environments in a vecenv). Could you provide a snippet to demo why it does not? 
I tried running the following:
```
import gym 
from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv
from time import sleep
n = 4

def make_env():
    return gym.make('PongNoFrameskip-v4')

venv = SubprocVecEnv([make_env]*n)
venv.reset()
venv.render()
sleep(3)
for _ in range(2000):
    venv.step([venv.action_space.sample() for _ in range(n)])
    venv.render()

sleep(3)
venv.reset()
venv.render()
sleep(3)
``` 
and it seems like all environments are being reset at the same time when venv.reset() is called.

**Comment by pzhokhov** [comment] 2018-11-19 20:00
I think what you are referring to is environment made with make_env_2 returning a mid-game observation (instead of that green-ish observation in other cases) when reset is called... Yes, I can reproduce that. Let me see why that happens... I am not convinced that's because of VecEnvs though. Will post here when I find anything.

**Comment by DanielTakeshi** [comment] 2018-11-19 20:20
@pzhokhov OK thanks. Yes that's what I meant, it is probably not due to VecEnv but something else in the pipeline.

**Comment by pzhokhov** [comment] 2018-11-19 21:36
ok so here's what I found. The non-green observation after reset is due to to NoopResetEnv and FireResetEnv wrappers in atari_wrappers (the latter automatically hits fire after reset, the former - several no-ops after reset()) . However, the more interesting part is that game counter is not being reset with venv.reset(), and that is due to EpisodicLifeReset() environment, which literally prevents resets if if the game is not over (the trick there is that it returns dones more at the end of each life, but only allows reset() to be called at the end of all lives).
In other words, feature, not a bug :) If you have a particular use case in which that's undesirable, you can pass {'episode_life'=False} in wrapper_kwargs argument to make_vec_env, like this: 
```
import gym 
from baselines.common.vec_env.subproc_vec_env import SubprocVecEnv
from baselines.common.vec_env.vec_frame_stack import VecFrameStack
from baselines.common.cmd_util import common_arg_parser, parse_unknown_args, make_vec_env
from time import sleep
import numpy as np

def make_env():
    return gym.make('PongNoFrameskip-v4')


def make_env_2(env_id, env_type='atari', nenv=1, seed=1, frame_stack_size=4):
	env = VecFrameStack(make_vec_env(env_id, env_type, nenv, seed, ), frame_stack_size)
	return env


def test(venv):
    venv.reset()
    venv.render()
    sleep(3)
    for _ in range(1000):
        actions = np.array([venv.action_space.sample() for _ in range(n)])
        venv.step(actions)
        venv.render()
    
    sleep(3)
    venv.reset()
    venv.render()
    sleep(3)
    print("Now playing second time, with a reset env")

    for _ in range(1000):
        actions = np.array([venv.action_space.sample() for _ in range(n)])
        venv.step(actions)
        venv.render()
    venv.close()


if __name__ == "__main__":
    n = 4

    # This works as expected
    venv = SubprocVecEnv([make_env]*n)
    test(venv)

    # This runs into trouble with the bench monitor?
    venv = make_env_2(env_id='PongNoFrameskip-v4', nenv=n)
    test(venv)
 ```

**Comment by pzhokhov** [comment] 2018-11-19 21:39
Note that this wrapper, EpisodicLifeEnv, applies by default only to atari, and only to the games that have a notion of "life" in them. Closing this, please reopen if something in the example above does not work.

**Closed by pzhokhov** 2018-11-19 21:39 UTC
