### ISSUE TITLE
ModuleNotFoundError: No module named 'baselines.common.atari_wrappers_deprecated'

### ISSUE THREAD

**Issue by adammcnamara** [openai/baselines#190] opened 2017-11-02 21:16 UTC
This method is referenced in three places:

1. https://github.com/openai/baselines/blob/bb403781182c6e31d3bf5de16f42b0cb0d8421f7/baselines/deepq/experiments/atari/enjoy.py#L15
2. https://github.com/openai/baselines/blob/bb403781182c6e31d3bf5de16f42b0cb0d8421f7/baselines/deepq/experiments/atari/wang2015_eval.py#L10
3. https://github.com/openai/baselines/blob/bb403781182c6e31d3bf5de16f42b0cb0d8421f7/baselines/deepq/experiments/atari/train.py#L25

Should this instead be?
```
from baselines.common.atari_wrappers import wrap_deepmind
```

**Comment by wchli** [comment] 2017-12-19 05:45
same problem

**Comment by h8907283** [comment] 2018-02-07 15:13
Changing the module import from:

from baselines.common.atari_wrappers_deprecated import wrap_dqn

to

from baselines.common.atari_wrappers import wrap_deepmind

doesn't work.

BTW, I did a git clone on gym and baselines last night, so there is nothing out-of-date.

**Comment by pzhokhov** [comment] 2018-11-14 22:38
cannot reproduce in the latest version, closing this

**Closed by pzhokhov** 2018-11-14 22:38 UTC
