### ISSUE TITLE
"deepq" or "deepq_1"

### ISSUE THREAD

**Issue by HuTobias** [openai/baselines#700] opened 2018-11-05 16:07 UTC
I wanted to get at the intermediate results of the layers of my deepq agent (e.g. the result of the first convolutional layer). 

I tried to look at the graph in tensorboard by using the old save_state function and i see two deepq graphs which are pretty similar. 

I also tried printing all the operations in my graph by inserting  
`graph = tf.get_default_graph() `
`for op in graph.get_operations():`
`    logger.log(op.values() )`

in deepq.learn after the lines 
`action = act(np.array(obs)[None], update_eps=update_eps, **kwargs)[0]`
`env_action = action`.

And again I am getting alot of operations with "deepq_1" in their name which are duplicates of "deepq" ones.

Is "deepq" or "deepq_1" used when I run
`python -m baselines.run --alg=deepq --env=BreakoutNoFrameskip-v4 --num_timesteps=1e6`?

**Comment by pzhokhov** [comment] 2018-11-05 19:46
This is related to the separate "act" and "train" functions (used for acting and training respectively). Ideally, we'd like to have them in separate scopes, however, because they need to share variables, we use the same scope name. Because some operations overlap, tensorflow automatically creates a scope "deepq_1" for those . This is not a bug, but I agree that this looks a little bit confusing in tensorboard. 

As for your direct question, which one of the scopes to use to get results of the first convolutional layer - if you want it at the time of interaction with environment, use deepq scope (that's the one created by build_act). If you need the results from during training (i.e. when computing weight updates), use deepq_1. Closing this, please reopen if that does not help.

**Closed by pzhokhov** 2018-11-05 19:46 UTC
Labels: question
